version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20
      python: 3.11
    commands:
      - echo Installing dependencies...
      - pip install --upgrade pip
      - pip install -r requirements.txt || true  # If you have requirements.txt

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 574720314262.dkr.ecr.ap-south-1.amazonaws.com
      - REPOSITORY_URI=574720314262.dkr.ecr.ap-south-1.amazonaws.com/flask-backend
      - IMAGE_TAG=latest

  build:
    commands:
      - echo Building Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - echo Pushing image to ECR...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Generating imagedefinitions.json...
      - printf '[{"name":"my-container","imageUri":"%s"}]' "$REPOSITORY_URI:$IMAGE_TAG" > imagedefinitions.json

  post_build:
    commands:
      - echo Deploying to ECS...
      - aws ecs update-service \
          --cluster final-test-cluster \
          --service final-test-service \
          --force-new-deployment \
          --region ap-south-1

artifacts:
  files:
    - imagedefinitions.json
