version: 0.2

env:
  variables:
    AWS_REGION: "ap-south-1"

phases:
  install:
    commands:
      - echo "Installing Terraform..."
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
      - terraform version

  pre_build:
    commands:
      - echo "Initializing Terraform..."
      - terraform init

  build:
    commands:
      - echo "Running Terraform plan..."
      - terraform plan
      - echo "Applying Terraform to provision infrastructure..."
      - terraform apply -auto-approve || echo "Terraform apply failed — might be due to existing resources"
